import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Field,Feedback,Modal,Resource} from './shared';
import {useAction,useLiveResource,useResource} from './hooks';
import {encode,type Client} from './lib/api';
type Policy={enabled:boolean;timezone:string;refresh_minutes:number;audit_minutes:number;automatic_repair:boolean};
type Mapping={source_id:number;guide_id:string;observed_name:string;current_name:string|null;pinned:boolean;priority:number};
type Family={id:string;name:string;feed:string;market:string;mappings:Mapping[];coverage:{current_programme:null|{title:string};coverage_24_hours:number;coverage_72_hours:number;overlaps:number;gaps:{start:number;end:number}[];needs_attention:boolean}};
type GuideChannel={source_id:number;guide_id:string;name:string};
type Summary={settings:Policy;sources:{id:number;name:string;provider_id:number|null;enabled:boolean;updated_at:number|null;attempt_at:number|null;reason:string|null;next_refresh:number;mode?:string}[];channels:Family[];guide_channels:GuideChannel[];last_run:{state:string;reason:string|null;last_start:number|null;last_finish:number|null};next_audit:number};
type Preview={revision:string;preserved:number;additions:{source_id:number;guide_id:string;start:number;end:number;programme:{title:string}}[]};
const date=(v:number|null,tz?:string)=>v?new Date(v*1000).toLocaleString(undefined,tz?{timeZone:tz}:undefined):'—';
export function FamilyGuides({api,close,initialChannel}:{api:Client;close:()=>void;initialChannel?:string}){
 const[search,setSearch]=useState('');const[query,setQuery]=useState('');const[source,setSource]=useState('');const[channel,setChannel]=useState(initialChannel??'');const action=useAction();
 const resource=useLiveResource<Summary>(api,`/guides?search=${encode(query)}${source?`&source_id=${source}`:''}`,5000);
 const current=resource.data?.channels.find(c=>c.id===channel);
 return <Modal open onOpenChange={open=>{if(!open)close()}} title="Programme guides" description="Store schedules independently of video providers. East, West and local stations keep exact guide mappings."><div className="space-y-4"><Feedback error={action.error}/><Resource {...resource}>{resource.data&&<>
 <Settings api={api} initial={resource.data.settings} saved={resource.reload}/><AddSource api={api} saved={resource.reload}/>
 <div className="flex flex-wrap gap-2"><Button disabled={action.busy||['queued','running','cancel_requested'].includes(resource.data.last_run.state)} onClick={()=>void action.run(async()=>{await api('/guides/run','POST');resource.reload()})}>Refresh guides now</Button><Button variant="outline" disabled={action.busy||!['queued','running','cancel_requested'].includes(resource.data.last_run.state)} onClick={()=>void action.run(async()=>{await api('/guides/cancel','POST');resource.reload()})}>Cancel guide refresh</Button></div>
 <p>Last run: {resource.data.last_run.state} · {date(resource.data.last_run.last_finish)} · Next coverage audit: {date(resource.data.next_audit)}</p>
 <ul className="space-y-2">{resource.data.sources.map(s=><li key={s.id} className="rounded-md border p-3"><strong>{s.name}</strong> · {s.enabled?'Enabled':'Disabled'}{s.mode==='selected_channels'&&<p>Using schedules for your selected channels.</p>}<p>Last valid data: {date(s.updated_at)} · next refresh: {date(s.next_refresh)}</p>{s.reason&&<p>{s.reason.replaceAll('_',' ')}; previous listings retained.</p>}<Button variant="outline" disabled={action.busy} onClick={()=>void action.run(async()=>{await api(`/guides/sources/${s.id}`,'PATCH',{enabled:!s.enabled});resource.reload()})}>{s.enabled?'Disable':'Enable'} {s.name}</Button></li>)}</ul>
 <label className="grid gap-2 text-sm">Family channel<select className="rounded-md border bg-background p-2" value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Choose a channel</option>{resource.data.channels.map(c=><option key={c.id} value={c.id}>{c.name} · {c.coverage.needs_attention?'Guide needs attention':'Covered'}</option>)}</select></label>
 {current&&<><p>{current.feed}{current.market?` · ${current.market}`:''} · Now: {current.coverage.current_programme?.title??'Missing guide'}</p><p>{current.coverage.coverage_24_hours.toFixed(1)} / 24 hours covered · {current.coverage.coverage_72_hours.toFixed(1)} / 72 hours covered · {current.coverage.overlaps} overlaps</p><ul>{current.coverage.gaps.slice(0,5).map(g=><li key={`${g.start}:${g.end}`}>Gap: {date(g.start,resource.data!.settings.timezone)} – {date(g.end,resource.data!.settings.timezone)}</li>)}</ul>
 <div className="space-y-2">{current.mappings.map(m=><div key={`${m.source_id}:${m.guide_id}`} className="rounded-md border p-2">{resource.data!.sources.find(s=>s.id===m.source_id)?.name} · {m.observed_name} · {m.pinned?'Pinned':'Automatic'} · priority {m.priority}{m.current_name!==m.observed_name&&<p>Guide identity changed; verify again.</p>}<Button variant="outline" disabled={action.busy} onClick={()=>void action.run(async()=>{await api(`/guides/channels/${encode(current.id)}`,'PATCH',{...m,current_name:undefined,pinned:undefined,remove:true});resource.reload()})}>Reject mapping {m.observed_name}</Button></div>)}</div>
 <Repair key={current.id} api={api} channel={current} timezone={resource.data.settings.timezone} saved={resource.reload}/>
 <form className="flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();setQuery(search)}}><label className="grid gap-2 text-sm">Guide source<select className="rounded-md border bg-background p-2" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{resource.data.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><Field label="Search guide channel names" value={search} onChange={e=>setSearch(e.target.value)}/><Button type="submit" variant="outline">Search guide channels</Button></form>
 <p className="text-sm text-muted-foreground">Up to 100 results are shown; narrow the search to find a specific station. A name without a regional marker requires your verification.</p>
 {resource.data.guide_channels.map(g=><Pin key={`${current.id}:${g.source_id}:${g.guide_id}:${g.name}`} api={api} family={current} guide={g} sourceName={resource.data!.sources.find(s=>s.id===g.source_id)?.name??'Source'} saved={resource.reload}/>)}
 </>}
 </>}</Resource></div></Modal>
}
function Settings({api,initial,saved}:{api:Client;initial:Policy;saved:()=>void}){const[value,setValue]=useState(initial);const action=useAction();return <form className="space-y-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api('/guides','PATCH',value);saved()})}}><label className="flex flex-wrap gap-2"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/>Enable scheduled guide refresh and audits</label><label className="flex flex-wrap gap-2"><input type="checkbox" checked={value.automatic_repair} onChange={e=>setValue({...value,automatic_repair:e.target.checked})}/>Fill verified guide gaps automatically</label><div className="grid gap-3 sm:grid-cols-3"><Field label="Household timezone (IANA)" required value={value.timezone} onChange={e=>setValue({...value,timezone:e.target.value})}/><Field label="Guide refresh interval (minutes)" required type="number" min={15} max={10080} value={value.refresh_minutes} onChange={e=>setValue({...value,refresh_minutes:Number(e.target.value)})}/><Field label="Coverage audit interval (minutes)" required type="number" min={15} max={1440} value={value.audit_minutes} onChange={e=>setValue({...value,audit_minutes:Number(e.target.value)})}/></div><p className="text-sm text-muted-foreground">The household timezone controls display, including daylight saving time. It never shifts East schedules into West schedules. Aim for seven days where a source provides it; missing intervals remain visible.</p><Button type="submit" variant="outline" disabled={action.busy}>Save guide settings</Button><Feedback error={action.error}/></form>}
function AddSource({api,saved}:{api:Client;saved:()=>void}){const[name,setName]=useState('');const[url,setUrl]=useState('');const[provider,setProvider]=useState('');const providers=useResource<{id:number;name:string}[]>(api,'/providers');const action=useAction();return <form className="space-y-3 rounded-md border p-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api('/guides/sources','POST',{name,...(provider?{provider_id:Number(provider)}:{url})});setName('');setUrl('');saved()})}}><Field label="Guide source name" required maxLength={128} value={name} onChange={e=>setName(e.target.value)}/><label className="grid gap-2 text-sm">Use provider XMLTV<select className="rounded-md border bg-background p-2" value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Enter an XMLTV URL</option>{providers.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{!provider&&<Field label="XMLTV URL" type="url" required maxLength={4096} value={url} onChange={e=>setUrl(e.target.value)}/>}<p className="text-sm text-muted-foreground">Oversized provider feeds automatically use schedules for up to 100 selected channels. XMLTV sources are limited to 32 MiB, 50,000 guide channels and 250,000 programmes per refresh. URLs may contain private credentials and are not returned in status responses.</p><Button type="submit" disabled={action.busy}>Add guide source</Button><Feedback error={action.error||providers.error}/></form>}
function Pin({api,family,guide,sourceName,saved}:{api:Client;family:Family;guide:GuideChannel;sourceName:string;saved:()=>void}){const[verified,setVerified]=useState(false);const[priority,setPriority]=useState(0);const action=useAction();return <form className="space-y-2 rounded-md border p-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api(`/guides/channels/${encode(family.id)}`,'PATCH',{source_id:guide.source_id,guide_id:guide.guide_id,observed_name:guide.name,verified,priority});saved()})}}><strong>{guide.name}</strong><p>{sourceName} · {guide.guide_id}</p><label className="flex flex-wrap gap-2"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified this guide is {family.name}, including its US English feed and local market.</label><Field label={`Guide priority for ${guide.name} (lower first)`} type="number" min={0} max={1000} value={priority} onChange={e=>setPriority(Number(e.target.value))}/><Button type="submit" variant="outline" disabled={!verified||action.busy}>Pin {guide.name}</Button><Feedback error={action.error}/></form>}
function Repair({api,channel,timezone,saved}:{api:Client;channel:Family;timezone:string;saved:()=>void}){const[preview,setPreview]=useState<Preview>();const action=useAction();return <div className="space-y-2"><Button variant="outline" disabled={action.busy} onClick={()=>void action.run(async()=>setPreview(await api<Preview>(`/guides/channels/${encode(channel.id)}/repair`,'POST',{apply:false})))}>Preview guide repair</Button>{preview&&<><p>{preview.preserved} existing programmes retained; {preview.additions.length} compatible programmes can fill holes.</p><ul>{preview.additions.slice(0,20).map(p=><li key={`${p.source_id}:${p.start}`}>{date(p.start,timezone)} · {p.programme.title} · source {p.source_id}</li>)}</ul><Button disabled={action.busy||!preview.additions.length} onClick={()=>void action.run(async()=>{await api(`/guides/channels/${encode(channel.id)}/repair`,'POST',{apply:true,revision:preview.revision});setPreview(undefined);saved()})}>Apply previewed repair</Button></>}<Feedback error={action.error}/></div>}
