import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Field,Feedback,Modal,Resource} from './shared';
import {useAction,useLiveResource} from './hooks';
import {encode,type Client} from './lib/api';
type Policy={enabled:boolean;interval_minutes:number;sample_seconds:number;concurrency:number;startup_seconds:number;budget_seconds:number;max_sample_mib:number;retry_minutes:number[];reserve_multiplier:number};
type Candidate={id:string;channel_ids?:string[];name:string;provider:string;disabled:boolean;excluded_until:number;state:string;reason:string|null;at:number|null;next_check:number;sample:null|{startup_ms?:number;sample_seconds?:number;sample_bytes?:number;video_codec?:string;audio_codec?:string;width?:number;height?:number}};
type Summary={settings:Policy;candidates:Candidate[];checking:string[]};
const date=(n:number|null)=>n?new Date(n*1000).toLocaleString():'Not checked';
const words=(s:string)=>s.replaceAll('_',' ');
export function FamilyHealth({api,close,initialChannel}:{api:Client;close:()=>void;initialChannel?:string}){
 const resource=useLiveResource<Summary>(api,'/stream-health');const[search,setSearch]=useState('');const[channel,setChannel]=useState(initialChannel);const[page,setPage]=useState(0);
 const candidates=resource.data?.candidates.filter(c=>(!channel||c.channel_ids?.includes(channel))&&`${c.name} ${c.provider}`.toLowerCase().includes(search.toLowerCase()))??[];
 return <Modal open onOpenChange={open=>{if(!open)close()}} title="Stream health" description="Check advancing decoded media, retain failed candidates for rechecks, and control manual exclusions."><div className="space-y-4"><Resource {...resource}>{resource.data&&<>
 <Settings api={api} initial={resource.data.settings} saved={resource.reload}/>
 <p className="text-sm text-muted-foreground">Checks share account limits with viewing and use one connection per pool. Viewers cancel probes before reusing their slots. Retry intervals include a small timing variation. Active playback is observed instead of opening another input.</p>
 {channel&&<Button variant="outline" onClick={()=>setChannel(undefined)}>Show all channels</Button>}
 <Field label="Find candidate" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/>
 <div className="space-y-3">{candidates.slice(page*50,page*50+50).map(c=><CandidateRow key={c.id} api={api} candidate={c} checking={resource.data!.checking?.includes(c.id)??false} saved={resource.reload}/>)}</div>
 {!candidates.length&&<p>No mapped candidates match your search.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Previous candidates</Button><Button variant="outline" disabled={(page+1)*50>=candidates.length} onClick={()=>setPage(page+1)}>Next candidates</Button></div>
 </>}</Resource></div></Modal>
}
function Settings({api,initial,saved}:{api:Client;initial:Policy;saved:()=>void}){
 const[settings,setSettings]=useState(initial);const action=useAction();
 return <form className="space-y-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api('/stream-health','PATCH',settings);saved()})}}><label className="flex flex-wrap gap-2"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Enable automatic health checks</label><div className="grid gap-3 sm:grid-cols-3"><Field label="Healthy standby interval (minutes)" type="number" required min={15} max={10080} value={settings.interval_minutes} onChange={e=>setSettings({...settings,interval_minutes:Number(e.target.value)})}/><Field label="Media sample (seconds)" type="number" required min={4} max={15} value={settings.sample_seconds} onChange={e=>setSettings({...settings,sample_seconds:Number(e.target.value)})}/><Field label="Concurrent checks" type="number" required min={1} max={2} value={settings.concurrency} onChange={e=>setSettings({...settings,concurrency:Number(e.target.value)})}/>{(['startup_seconds','budget_seconds','max_sample_mib','reserve_multiplier'] as const).map(key=><Field key={key} label={({startup_seconds:'Startup limit (seconds)',budget_seconds:'Total check limit (seconds)',max_sample_mib:'Sample byte limit (MiB)',reserve_multiplier:'Reserve check interval multiplier'})[key]} type="number" required value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/>)}{settings.retry_minutes.map((minutes,index)=><Field key={index} label={`Failure retry ${index+1} (minutes)`} type="number" required min={1} max={10080} value={minutes} onChange={e=>setSettings({...settings,retry_minutes:settings.retry_minutes.map((n,i)=>i===index?Number(e.target.value):n)})}/>)}</div><Button type="submit" variant="outline" disabled={action.busy}>Save health settings</Button><Feedback error={action.error}/></form>
}
function CandidateRow({api,candidate:c,checking,saved}:{api:Client;candidate:Candidate;checking:boolean;saved:()=>void}){
 const[disabled,setDisabled]=useState(c.disabled);const[minutes,setMinutes]=useState(0);const action=useAction();
 return <article className="space-y-2 rounded-md border p-3"><strong>{c.name}</strong><p>{c.provider} · {checking?'Checking':words(c.state)}{c.reason?` · ${words(c.reason)}`:''}</p><p className="text-sm text-muted-foreground">Observed: {date(c.at)} · Next check: {date(c.next_check)}</p>{c.sample&&<p className="text-sm">{c.sample.video_codec??'Codec unknown'} {c.sample.width&&c.sample.height?`${c.sample.width}×${c.sample.height}`:''} · audio {c.sample.audio_codec??'not reported'}{c.sample.startup_ms!==undefined?` · first media bytes ${c.sample.startup_ms} ms`:''}{c.sample.sample_seconds!==undefined?` · ${c.sample.sample_seconds.toFixed(1)} seconds observed`:''}</p>}
 <Button variant="outline" disabled={action.busy||checking} onClick={()=>void action.run(async()=>{await api(`/stream-health/${encode(c.id)}/check`,'POST');saved()})}>Check {c.name}</Button>
 <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api(`/stream-health/${encode(c.id)}`,'PATCH',{disabled,exclude_minutes:minutes});saved()})}}><label className="flex flex-wrap gap-2"><input type="checkbox" checked={disabled} onChange={e=>setDisabled(e.target.checked)}/>Manually disable {c.name}</label><Field label={`Exclude ${c.name} for minutes (0 clears)`} type="number" required min={0} max={10080} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><Button variant="outline" type="submit" disabled={action.busy}>Save exclusion for {c.name}</Button></form>{c.excluded_until>0&&<p>Exclusion expires {date(c.excluded_until)}</p>}<Feedback error={action.error}/></article>
}
