import {Button} from '@/components/ui/button';
import {Feedback,Modal,Resource,words} from './shared';
import {useAction,useLiveResource} from './hooks';
import type {Client} from './lib/api';
export type FamilyAction='accounts'|'matching'|'health'|'guides'|'catalog';
type Summary={paused:boolean;attention:{id:string;title:string;reason:string;count?:number;retry_at?:number;action:FamilyAction;channel_id?:string}[];sharing:{viewers:number;workers:number;groups:{viewers:number;state:string}[]};pools:{id:number;name:string;local_reservations:number;estimated_free:number;confidence:string;usage_age_seconds:number|null}[];changes:{id:number;at:number;kind:string;target:string;undone:boolean}[];recovery_events:{at:number;channel_id:string;reason:string;generation:number}[];selections:{channel_id:string;details:{at:number;attempts:{candidate_id:string;reason:string;estimated_free_before?:number;confidence?:string}[]}}[];catalog:{next_run:number|null;last_run:null|{state:string}};guide:{state:string;last_finish:number|null;reason:string|null}};
const date=(v:number|null)=>v?new Date(v*1000).toLocaleString():'—';
export function FamilyActivity({api,close,open}:{api:Client;close:()=>void;open:(action:FamilyAction,channel?:string)=>void}){
 const resource=useLiveResource<Summary>(api,'/activity',3000);const action=useAction();
 return <Modal open onOpenChange={value=>{if(!value)close()}} title="Activity and attention" description="Resolve exceptions here while automatic maintenance handles routine work."><div className="space-y-4"><Feedback error={action.error}/><Resource {...resource}>{resource.data&&<>
 <div className="flex flex-wrap gap-2"><Button variant={resource.data.paused?'default':'outline'} disabled={action.busy} onClick={()=>void action.run(async()=>{await api('/activity/pause','POST',{paused:!resource.data!.paused});resource.reload()})}>{resource.data.paused?'Resume automation':'Pause all automation'}</Button>{(['accounts','matching','health','guides','catalog'] as FamilyAction[]).map(value=><Button key={value} variant="outline" onClick={()=>open(value)}>{value==='accounts'?'Account controls':value==='matching'?'Channel matching':value==='health'?'Stream health':value==='guides'?'Programme guides':'Catalog refresh'}</Button>)}</div>
 <p className="text-sm text-muted-foreground">Global pause cancels background work and preserves each schedule’s settings. It leaves healthy viewing alone. Manual checks remain available.</p>
 <p>{resource.data.sharing.viewers} viewers · {resource.data.sharing.workers} shared media workers</p>
 <ul>{resource.data.pools.map(pool=><li key={pool.id}>{pool.name}: {pool.local_reservations} local inputs, {pool.estimated_free} estimated free · {pool.confidence} · provider usage {pool.usage_age_seconds===null?'not observed':`${pool.usage_age_seconds}s old`}</li>)}</ul>
 <p>Catalog: {resource.data.catalog.last_run?.state??'Never run'} · next {date(resource.data.catalog.next_run)} · Guides: {resource.data.guide.state} · last finished {date(resource.data.guide.last_finish)}</p>
 <section className="space-y-2"><h3 className="font-semibold">Needs attention ({resource.data.attention.length})</h3>{!resource.data.attention.length&&<p>No current exceptions.</p>}{resource.data.attention.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-md border p-3"><div><strong>{item.title}</strong><p>{words(item.reason)}{item.count!==undefined?` · ${item.count}`:''}</p>{item.retry_at&&<p>Retry eligible {date(item.retry_at)}</p>}</div><Button variant="outline" onClick={()=>open(item.action,item.channel_id)}>Resolve {item.title}</Button></div>)}</section>
 <details><summary>Recent selection decisions</summary>{resource.data.selections.map(s=><div key={s.channel_id} className="my-2 rounded-md border p-2"><p>{s.channel_id} · {date(s.details.at)}</p>{s.details.attempts.map((attempt,i)=><p key={i}>{attempt.candidate_id}: {words(attempt.reason)}{attempt.estimated_free_before!==undefined?` · ${attempt.estimated_free_before} slots available before reservation`:''}{attempt.confidence?` · ${attempt.confidence}`:''}</p>)}</div>)}</details>
 <details><summary>Recent playback recovery</summary>{resource.data.recovery_events.map((event,i)=><p key={i}>{date(event.at)} · {event.channel_id} · {words(event.reason)} · generation {event.generation}</p>)}</details>
 <details><summary>Reversible setting changes</summary><p className="text-sm text-muted-foreground">Undo is available while that setting still matches the recorded change; newer edits are never overwritten.</p>{resource.data.changes.map(change=><div key={change.id} className="my-2 flex items-center justify-between gap-2 rounded-md border p-2"><p>{date(change.at)} · {words(change.kind)} {change.target}</p><Button variant="outline" disabled={change.undone||action.busy} onClick={()=>void action.run(async()=>{await api(`/activity/undo/${change.id}`,'POST');resource.reload()})}>{change.undone?'Undone':`Undo change ${change.id}`}</Button></div>)}</details>
 </>}</Resource></div></Modal>
}
