import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Card} from '@/components/ui/card';
import {Feedback,Resource} from './shared';
import {useAction,useResource} from './hooks';
import type {Client,Profile} from './lib/api';
const fieldClass='min-h-11 w-full rounded-md border bg-background px-3';
export function ParentUnlock({api,onUnlocked,onCancel}:{api:Client;onUnlocked:()=>void|Promise<void>;onCancel:()=>void}){
 const[pin,setPin]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const value=pin;setPin('');try{await api('/parent/unlock','POST',{pin:value});await onUnlocked()}catch(e){setError(e instanceof Error?e.message:'Could not unlock.')}finally{setBusy(false)}}}><p>Enter the household PIN to leave kids mode or manage this account.</p><label className="grid gap-2">Parent PIN<input className={fieldClass} autoFocus type="password" inputMode="numeric" autoComplete="off" maxLength={8} pattern="[0-9]{4,8}" required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><Feedback error={error}/><div className="flex gap-3"><Button disabled={busy} type="button" variant="outline" onClick={()=>{setPin('');onCancel()}}>Cancel</Button><Button disabled={busy} type="submit">{busy?'Unlocking…':'Unlock'}</Button></div></form>
}
type ParentStatus={pin_configured:boolean;unlocked:boolean;restricted:boolean};
type KidsSettings={enabled:boolean;max_age:number};
type Approval={id:string;type:string;name?:string};
function PinSettings({api,configured,onSaved}:{api:Client;configured:boolean;onSaved:()=>void}){
 const[current,setCurrent]=useState('');const[pin,setPin]=useState('');const a=useAction();
 async function save(remove=false){const body={pin:remove?'':pin,...(configured?{current_pin:current}:{})};setCurrent('');setPin('');await a.run(async()=>{await api('/parent/pin','PUT',body);onSaved()},remove?'Parent PIN removed.':'Parent PIN saved.')}
 return <form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={a.busy} className="space-y-4"><legend className="mb-3 font-semibold">Household PIN</legend><p className="text-sm text-muted-foreground">Use a 4–8 digit PIN to protect leaving kids profiles. Keep it private. Turn off kids mode on all profiles before removing the PIN.</p>{configured&&<label className="grid gap-2">Current PIN<input className={fieldClass} type="password" autoComplete="off" inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} required value={current} onChange={e=>setCurrent(e.target.value.replace(/\D/g,''))}/></label>}<label className="grid gap-2">New PIN<input className={fieldClass} type="password" autoComplete="new-password" inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><Feedback error={a.error} success={a.success}/><div className="flex flex-wrap gap-3"><Button type="submit">Save parent PIN</Button>{configured&&<Button type="button" variant="outline" disabled={!/^[0-9]{4,8}$/.test(current)} onClick={()=>void save(true)}>Remove PIN</Button>}</div></fieldset></form>
}
function KidsForm({api,profile,initial,configured,onChanged}:{api:Client;profile:string;initial:KidsSettings;configured:boolean;onChanged?:()=>Promise<void>}){
 const[settings,setSettings]=useState(initial);const a=useAction();
 return <form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await api(`/profiles/${encodeURIComponent(profile)}/kids`,'PUT',settings);await onChanged?.()},'Kids settings saved.')}}><fieldset disabled={a.busy} className="space-y-4"><legend className="mb-3 font-semibold">Content restrictions</legend><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={settings.enabled} disabled={!configured} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Kids profile</label>{!configured&&<p>Set a household PIN first to enable kids mode.</p>}<label className="grid gap-2">Maximum age<select className={fieldClass} value={settings.max_age} onChange={e=>setSettings({...settings,max_age:Number(e.target.value)})}>{Array.from({length:18},(_,age)=><option key={age} value={age}>{age===0?'All ages':`${age} years`}</option>)}</select></label><p className="text-sm text-muted-foreground">Unrated or conflicting titles stay hidden until a parent approves the exact title. Live TV uses the Family Kids channel list, not age ratings for each programme. Review those channels in Family lineup: some feeds change content at night.</p><Feedback error={a.error} success={a.success}/><Button type="submit">Save kids settings</Button></fieldset></form>
}
function ParentTitleSearch({api,busy,approve}:{api:Client;busy:boolean;approve:(id:string,type:string,approved:boolean)=>Promise<void>}){
 const[query,setQuery]=useState('');const[type,setType]=useState('movie');const[path,setPath]=useState<string|null>(null);
 const r=useResource<{items:Approval[]}>(api,path);
 return <div className="space-y-3"><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();if(!query.trim())return;const next=`/parent/search?type=${type}&search=${encodeURIComponent(query.trim())}`;if(next===path)r.reload();else setPath(next)}}><label className="grid gap-2">Find a title<input className={fieldClass} type="search" required maxLength={128} value={query} onChange={e=>{setQuery(e.target.value);setPath(null)}}/></label><label className="grid gap-2">Search type<select className={fieldClass} value={type} onChange={e=>{setType(e.target.value);setPath(null)}}><option value="movie">Movies</option><option value="series">Series</option></select></label><Button disabled={r.loading||!query.trim()} type="submit">{r.loading?'Searching…':'Search titles'}</Button></form>{path&&<Resource {...r}><ul className="max-h-80 space-y-3 overflow-y-auto" aria-label="Title search results">{r.data?.items.slice(0,40).map(item=><li className="flex items-center justify-between gap-3 rounded-md border p-3" key={`${item.type}:${item.id}`}><span className="min-w-0 break-words">{item.name||item.id}<small className="block text-muted-foreground">{item.type}</small></span><Button type="button" variant="outline" disabled={busy} aria-label={`Approve ${item.name||item.id}`} onClick={()=>void approve(item.id,item.type,true)}>Approve</Button></li>)}</ul>{r.data?.items.length===0&&<p>No matching titles. Try another name or use an exact title ID.</p>}</Resource>}</div>
}
function TitleApprovals({api,profile}:{api:Client;profile:string}){
 const path=`/profiles/${encodeURIComponent(profile)}/approvals`;const[offset,setOffset]=useState(0);const r=useResource<Approval[]>(api,offset?`${path}?offset=${offset}`:path);const a=useAction();const[id,setId]=useState('');const[type,setType]=useState('movie');
 async function approve(id:string,type:string,approved:boolean){await a.run(async()=>{await api(path,'POST',{id:id.trim(),type,approved});setId('');r.reload()},'Title approval saved.')}
 return <section className="space-y-4"><h3 className="font-semibold">Approved titles</h3><p className="text-sm text-muted-foreground">Approved titles appear in this profile’s kids library. Search by name and review the title before approving it. The server verifies its identity. Up to 500 approved titles are supported per profile; revoke a title before adding more.</p><ParentTitleSearch api={api} busy={a.busy} approve={approve}/><details><summary className="cursor-pointer py-3 text-sm">Use an exact title ID</summary><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void approve(id,type,true)}}><label className="grid gap-2">Exact title ID<input className={fieldClass} required maxLength={256} value={id} onChange={e=>setId(e.target.value)}/></label><label className="grid gap-2">Title type<select className={fieldClass} value={type} onChange={e=>setType(e.target.value)}><option value="movie">Movie</option><option value="series">Series</option></select></label><Button disabled={a.busy} type="submit">Approve title</Button></form></details><Feedback error={a.error} success={a.success}/><Resource {...r}><ul className="max-h-80 space-y-3 overflow-y-auto">{r.data?.map(item=><li className="flex items-center justify-between gap-3" key={`${item.type}:${item.id}`}><span className="min-w-0 break-words">{item.name||item.id} <small>({item.type})</small></span><Button variant="outline" disabled={a.busy} onClick={()=>void approve(item.id,item.type,false)}>Revoke</Button></li>)}</ul>{r.data?.length===0&&<p>No approved titles on this page.</p>}<div className="flex flex-wrap gap-3"><Button className="w-full sm:w-auto" variant="outline" disabled={a.busy||r.loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-500))}>Previous approvals</Button><Button className="w-full sm:w-auto" variant="outline" disabled={a.busy||r.loading||(r.data?.length??0)<500} onClick={()=>setOffset(offset+500)}>Next approvals</Button></div></Resource></section>
}
function ProfileKids({api,profile,configured,onChanged}:{api:Client;profile:string;configured:boolean;onChanged?:()=>Promise<void>}){
 const r=useResource<KidsSettings>(api,`/profiles/${encodeURIComponent(profile)}/kids`);
 return <Resource {...r}>{r.data&&<div className="space-y-6"><KidsForm api={api} profile={profile} initial={r.data} configured={configured} onChanged={onChanged}/><TitleApprovals api={api} profile={profile}/></div>}</Resource>
}
export function ParentalControls({api,profiles,onChanged}:{api:Client;profiles:Profile[];onChanged?:()=>Promise<void>}){
 const r=useResource<ParentStatus>(api,'/parent/status');const[profile,setProfile]=useState(profiles[0]?.id??'');
 return <Card className="space-y-6 p-4 sm:p-6"><h2 className="text-lg font-semibold">Parental controls</h2><Resource {...r}>{r.data&&<><PinSettings api={api} configured={r.data.pin_configured} onSaved={r.reload}/><label className="grid gap-2">Manage kids profile<select className={fieldClass} value={profile} onChange={e=>setProfile(e.target.value)}>{profiles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{profile&&<ProfileKids key={profile} api={api} profile={profile} configured={r.data.pin_configured} onChanged={onChanged}/>}</>}</Resource></Card>
}
